In [11]:
import numpy as np
import pandas as pd

In [12]:
data=pd.read_csv("/home/sasmiya/Downloads/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [13]:
dt=data

In [14]:
dt

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No     1.0   
1     5575-GNVDE     NaN              0      No         No    34.0   
2     3668-QPYBK    Male              0      No         No     2.0   
3     7795-CFOCW    Male              0     NaN         No    45.0   
4     9237-HQITU  Female              0      No         No     2.0   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes    24.0   
7039  2234-XADUH  Female              0     Yes        Yes    72.0   
7040  4801-JZAZL  Female              0     Yes        Yes    11.0   
7041  8361-LTMKD    Male              1     Yes         No     4.0   
7042  3186-AJIEK    Male              0      No         No    66.0   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             NaN            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70           NaN   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [6]:
dt.shape

(7043, 21)

In [15]:
dt.isnull()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0          False   False          False    False       False   False   
1          False    True          False    False       False   False   
2          False   False          False    False       False   False   
3          False   False          False     True       False   False   
4          False   False          False    False       False   False   
...          ...     ...            ...      ...         ...     ...   
7038       False   False          False    False       False   False   
7039       False   False          False    False       False   False   
7040       False   False          False    False       False   False   
7041       False   False          False    False       False   False   
7042       False   False          False    False       False   False   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0            False          False            False           False  ...   
1            False          False             True           False  ...   
2            False          False            False           False  ...   
3            False          False            False           False  ...   
4            False          False            False           False  ...   
...            ...            ...              ...             ...  ...   
7038         False          False            False           False  ...   
7039         False          False            False           False  ...   
7040         False          False            False           False  ...   
7041         False          False            False           False  ...   
7042         False          False            False           False  ...   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                False        False        False            False     False   
1                False        False        False            False     False   
2                False        False        False            False     False   
3                False        False        False            False     False   
4                False        False        False            False     False   
...                ...          ...          ...              ...       ...   
7038             False        False        False            False     False   
7039             False        False        False            False     False   
7040             False        False        False            False     False   
7041             False        False        False            False     False   
7042             False        False        False            False     False   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                False          False           False         False  False  
1                False          False           False         False  False  
2                False          False           False         False  False  
3                False          False           False         False  False  
4                False          False           False          True  False  
...                ...            ...             ...           ...    ...  
7038             False          False           False         False  False  
7039             False          False           False         False  False  
7040             False          False           False         False  False  
7041             False          False           False         False  False  
7042             False          False           False         False  False  

[7043 rows x 21 columns]

In [16]:
dt.isnull().sum()

customerID          0
gender              1
SeniorCitizen       0
Partner             1
Dependents          0
tenure              1
PhoneService        0
MultipleLines       0
InternetService     1
OnlineSecurity      2
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [18]:
dt.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure              float64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [20]:
dt['gender'].mode()[0]

'Male'

In [22]:
dt['gender']=data['gender'].fillna(dt['gender'].mode()[0])

In [23]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             1
Dependents          0
tenure              1
PhoneService        0
MultipleLines       0
InternetService     1
OnlineSecurity      2
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [25]:
dt['Partner'].mode()[0]

'No'

In [26]:
dt['Partner']=dt['Partner'].fillna(dt['Partner'].mode()[0])

In [27]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              1
PhoneService        0
MultipleLines       0
InternetService     1
OnlineSecurity      2
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [28]:
dt['tenure'].median()

29.0

In [31]:
dt['tenure']=dt['tenure'].fillna(dt['tenure'].median())

In [32]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     1
OnlineSecurity      2
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [33]:
dt['InternetService'].mode()[0]

'Fiber optic'

In [34]:
dt['InternetService']=dt['InternetService'].fillna(dt['InternetService'].mode()[0])

In [35]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      2
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [36]:
dt['OnlineSecurity'].mode()[0]

'No'

In [37]:
dt['OnlineSecurity']=dt['OnlineSecurity'].fillna(dt['OnlineSecurity'].mode()[0])

In [38]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         1
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [39]:
dt['TechSupport']=dt['TechSupport'].fillna(dt['TechSupport'].mode()[0])

In [40]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     3
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [41]:
dt['StreamingMovies']=dt['StreamingMovies'].fillna(dt['StreamingMovies'].mode()[0])

In [42]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      1
TotalCharges        4
Churn               0
dtype: int64

In [44]:
dt['MonthlyCharges']=dt['MonthlyCharges'].fillna(dt['MonthlyCharges'].median())

In [45]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        4
Churn               0
dtype: int64

In [46]:
dt['TotalCharges']=pd.to_numeric(data['TotalCharges'],errors='coerce')#to change data type into numeric

In [50]:
dt.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure              float64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [47]:
dt.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        15
Churn                0
dtype: int64

In [51]:
dt['TotalCharges']=dt['TotalCharges'].fillna(dt['TotalCharges'].mean())

In [52]:
dt.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [53]:
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No     1.0           No   
1  5575-GNVDE    Male              0      No         No    34.0          Yes   
2  3668-QPYBK    Male              0      No         No     2.0          Yes   
3  7795-CFOCW    Male              0      No         No    45.0           No   
4  9237-HQITU  Female              0      No         No     2.0          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No     Fiber optic            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85     29.850000     No  
1               Mailed check          56.95   1889.500000     No  
2               Mailed check          53.85    108.150000    Yes  
3  Bank transfer (automatic)          42.30   1840.750000     No  
4           Electronic check          70.70   2282.563083    Yes  

[5 rows x 21 columns]

In [54]:
dt1=dt

In [55]:
dt1.shape

(7043, 21)

In [57]:
dt1.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No     1.0           No   
1  5575-GNVDE    Male              0      No         No    34.0          Yes   
2  3668-QPYBK    Male              0      No         No     2.0          Yes   
3  7795-CFOCW    Male              0      No         No    45.0           No   
4  9237-HQITU  Female              0      No         No     2.0          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No     Fiber optic            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85     29.850000     No  
1               Mailed check          56.95   1889.500000     No  
2               Mailed check          53.85    108.150000    Yes  
3  Bank transfer (automatic)          42.30   1840.750000     No  
4           Electronic check          70.70   2282.563083    Yes  

[5 rows x 21 columns]

In [61]:
dt1=dt1.drop('customerID',axis=1)

In [63]:
dt1=pd.get_dummies(dt1)

In [64]:
dt1.shape

(7043, 47)

In [65]:
dt1.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', '

In [78]:
dt1.dtypes

SeniorCitizen                                int64
tenure                                     float64
MonthlyCharges                             float64
TotalCharges                               float64
gender_Female                                uint8
gender_Male                                  uint8
Partner_No                                   uint8
Partner_Yes                                  uint8
Dependents_No                                uint8
Dependents_Yes                               uint8
PhoneService_No                              uint8
PhoneService_Yes                             uint8
MultipleLines_No                             uint8
MultipleLines_No phone service               uint8
MultipleLines_Yes                            uint8
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
OnlineSecurity_No                            uint8
OnlineSecurity_No internet serv

In [79]:
dt=dt.drop('customerID',axis=1)

KeyError: "['customerID'] not found in axis"

In [80]:
x=dt.drop("Churn",axis=1)
y=dt['Churn']

In [81]:
x=pd.get_dummies(x)

In [82]:
x.shape

(7043, 45)

In [83]:
y.shape

(7043,)

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [86]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=1/3,random_state=0)

In [87]:
classifier = RandomForestClassifier()

In [88]:
classifier.fit(xtrain,ytrain)

/home/sasmiya/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [89]:
ypredict= classifier.predict(xtest)

In [90]:
ypredict

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [91]:
from sklearn.metrics import accuracy_score
accuracy_score(ypredict,ytest)

0.772572402044293

In [92]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

In [93]:
confusion_matrix(ypredict,ytest)#tp fp-fn tn

array([[1547,  352],
       [ 182,  267]])

In [94]:
precision_recall_fscore_support(ypredict,ytest)

(array([0.89473684, 0.43134087]),
 array([0.81463928, 0.59465479]),
 array([0.85281147, 0.5       ]),
 array([1899,  449]))